bin/tar.py

Much nicer verbose handling. Fixed excessive looping on extractall.

verbose fix to tar.py

---

bin/pip.py

#39 As a last resport pip will try to run setup.py.
pip looks for packages as follows:
* Look for a package folder using the name of the package.
* Look for a src folder
* Attempt to run setup.py

Pip - attempt setup.py handling

---

bin/alias.py
bin/clear.py
bin/copy.py
bin/cp.py
bin/grep.py
bin/ls.py
bin/paste.py
bin/sort.py
bin/uniq.py
bin/unzip.py

A few minor documentation updates:
Added docstrings for the scripts which didn't have one yet.
Also, the usage message of `cp` referred  to "moving". Fixed that as well.

Documentation updates, mainly added missing docstrings

---

bin/md5sum.py
bin/sha1sum.py
bin/sha256sum.py

I needed to get a md5 hash of a file so I added md5sum to stash. You can provide a filename and get the hash value or you can provide a txt file with md5 hashes and filenames to get a pass/fail on each file.
I'd like for md5sum to use pipes to allow text to be passed to it but I am unsure how it works.

md5sum added

---

bin/mail.py

Simple mail module to send messages and files through stash. It's not ready for a pull accept but I'd like feedback.

mail module

---

bin/crypt.py

crypt is a little file encryption module that uses AES in CBC mode to encrypt files. I'm contemplating adding public keys to encrypt the random passphrase for AES and including it with the encrypted file. I'm hoping to add more features but the AES portion seems to be working well.

initial crypt.py

---

bin/crypt.py

Moved to using simplecrypto package (wrapper for pycrypto). Encryption key method has changed so any previous encrypted files will be broke. I'm still working on adding pub key encryption but you can accept this pull request if you like.

using simplecrypto pypi package

---

bin/telnet.py

this is not a good long term solution, but someone requested telnet, and I wrote one some time ago.

Very simple telnet client.

---

bin/git.py

fixed handling of `git push remote` style entries, using remote shortcut
rather than full uri.
git remote command can now add new remote shortcut

added git fetch command.   updated handling of remote shortcuts

---

bin/git.py

Here is a set of safer git commands.  Most of the dangerous commands that modify real files warn before executing if there are any uncommitted changes.  Also, no more clearing working tree.
Also, reset is actually functional, allowing you to revert single files to another commit in the staging area.  Working tree files are not updated unless --shard is specified.    This allows one to rebase commits, sort of.

Safer git operations, better reset cmd

---

bin/telnet.py

Removed testing prints
Now sends carriage return

fixed <CR> and removed prints

---

bin/sqlite.py

sqlite is modeled after sqlite3 command-line.

added sqlite.py

---

README.md
bin/wol.py
lib/wakeonlan/LICENSE
lib/wakeonlan/wol.py

wol (wake on lan) command for stash, based on
https://github.com/remcohaszing/pywakeonlan.
Tested in my local network with Pythonista 1.6 beta,
but it should also work with 1.5

Implementation of Wake on LAN

---

README.md
bin/wol.py
stash.py

Better manipulation of sys.path, in particular avoiding constant growth

improved handling of sys.path

---

bin/gh.py

This adds a github (gh) command, with a fork, create, and pull (pull request) command.  This pull was created with the new command

Add gh github command

---

bin/gh.py

Can specify --issue, or --title, but not both.  If title, must also specify body, use default body to ensure correct args.  Also fix filename prinout

Fix gh pull arguments

---

bin/pip.py

Changed VersionSpecifier to parse requirement to conform to pep440.  Does not handle === or ~= correctly, but this could probably be extended.  Creates a set of operator/version pairs which must all pass to declare a hit.

pip version specifiers

---

bin/python.py

Changes to the python command:
-added a interactive console (started when not called with "-c","-m" or file argument)
-changed the way the command-line arguments are handled.
-changed the help-paramters to be more like CPython
-fixed a bug allowing to pass both "-c" and "-d" (it now prints an error-message)
-converted spaces to tabs (i edited this file in pythonista, it is annoying to see a mixture of tabs and spaces)

python command: added interactive console

---

bin/python.py

I have fixed a bug in python.py (i inadvertently uploaded a old version to github in my last commit).
I am sorry for breaking the python command.

fixed a bug in python.py

---

bin/gci.py
bin/mc.py

!This pull-request may contain english spoken by a non-native english-speaker!
I have added two new commands: gci and mc.
mc:
-name reffers to the command-line-tool "midnight commander" (this is definitly not a full counterpart)
-allows browsing files on other filesystems (currently supported: local, FTP and dropbox)
-allows browsing files on multiple filesystems synchronously.
-designed to be easily extendable (simply subclass BaseFSI and add it to INTERFACES)
-allows reading files on other filesystems
-allows copying and moving files between two filesystems (even between dropbox and FTP)
-allows "running" a command on a different filesystem (download files into a tempdir, cd into it, run command, cd back, upload files if changed)
-uses an internal command-loop (using the cmd-module) …

added new commands

---

bin/mc.py

the mc.py subcommand now accept names containing spaces.
This is done by using the shlex-module.
Example (in mc-command): cp 1 "space test.py" 2 "some other file.py"
The internal command calls by cp, move and exec will now call the command in such a way that spaced names will no longer result in errors.

mc.py: added support for filenames with spaces

---

.stash_tips
bin/gci.py
bin/mc.py
bin/selfupdate.py
bin/webviewer.py
lib/libcompleter.py

This pull request contains mostly minor bugfixes and improvements.
**New command**: `webviewer`
-opens the webbrowser without freezing StaSh
-implemented to fix `mc`
-named webviewer instead of webbrowser to prevent naming conflicts with the module
**Improvements**:
-`mc.py` and `gci.py` are now compatible with PEP8
-`mc.py` and `gci.py` now uses colors
-more autocompletion for commands
-`mc.py`: now supports non-integer IDs
-`mc.py`: now supports dropbox logout
-(!) `selfupdate.py` and `getstash.py`: now support updating from other users forks
-added a new tip to `.stash_tips.py`
**Bugfixes**:
-fixed some bugs in `mc.py` (dropbox setup should no longer freeze StaSh. Sorry, missed that bug before as i tested the dropbox setup outside StaSh)
**WARNING**: `selfupdate.py` and `getstash.py` …

New command, bugfixes and improvements

---

bin/head.py

I mistakenly sent pull request to master branch, so I resend pull request to dev branch.
This is intended to work same as `head` command in linux, except `-c` option is not implemented.
This depends on the fix #187.

Added head.py

---

bin/tail.py

This is intended to work same as tail command in linux.
This works better for stdin with the fix #194.

Added tail.py

---

bin/gh.py

This should hopefully facilitate people using ssh git mode.

Add gh list_keys and gh create_key to add ssh key to github account

---

bin/easy_config.py

The `easy_config`-command now provides a button to add a editor-shortcut for `launch_stash.py`.
This script requires [this module](https://gist.github.com/jsbain/c9f42c81c53b276b6560), which is automatically downloaded when the button is pressed for the first time. It is not downloaded when the command is run the first time to improve off-line capabilities.
@jsbain would you mind if i later include your `add_action.py`-module directly in `$STASH_ROOT/lib/`?

easy_config.py: added "Add Editor Shortcut"

---

bin/grep.py

Modified logic around selection of lines and coloring parts of line, which also rendered fn_predicate obsolete

Fixed issue #229: grep "x" | cat doesn't work

---

bin/git.py
lib/git/git-branch.py

- Cleanup unused getpass import
- Redact password on git push
- Add helpstring for git log --oneline
- Cleanup git remote output
- Cleanup git branch output

Minor git.py and git-branch.py improvements

---

bin/latte.py

Latte is a new package manager built for Latte. It may require updates in the future, so if you're going to accept this, make sure to be willing to accept more requests in the future.

Package manager for StaSh (read description please)

---

bin/cowsay.py
whatis.py

I have added two commands. 
`cowsay` which is really just entertainment 
`whatis` find what each command does
These commands are from Linux.

Added 2 new commands. cowsay and whatis

---

bin/pip.py

Hi,
This PR improves the handling of the `entry_points` keywordargument in the setup.py replacement used by `pip.py`.
This *should* fix #270.
Special thanks to @dgelessus for investigating the issue and providing significant support for fixing it.

pip.py: improve entry_point handling

---

CHANGES.md
README.md
docs/py3_todo.md

Hi everyone,
i have updated the `README.md`,  `CHANGELOG.md` and `docs/py3_todo.md` files to reflect the changes since version `0.6.0`. Can someone please proofread my changes? Did i forget anything?
Here are some interesting statistics:
- Its been 2 years since version `0.6.15`. During this time, 14 Contributors have made ~252 commits and changed 209 files ([Comparsion](https://github.com/ywangd/stash/compare/e514527ef97cd017f642ddf28f8604e82d69c284...dev)).
- Since version `0.6.0`, 14 Contributors have made ~407 commits and changed 227 files ([Comparsion](https://github.com/ywangd/stash/compare/1fd66c7138fcd04e18eb5c5bfc8b5a650c0519f5...dev)).
Since its been quite a while and some people on the forum still dont know about version `0.7.0`, should we make a update post in the forums? …

Update README.md and CHANGELOG.md

---

README.md

Let’s not ask people to pwn their pythonista right out of the gate.

Make installation link https

---

bin/easy_config.py
bin/gh.py
bin/git.py
bin/pip.py
core.py
lib/git/git-branch.py
lib/libversion.py
lib/stashutils/wheels.py
system/dummyobjc_util.py
system/shscreens.py
system/shterminal.py
tests/misc/test_libversion.py
tests/pip/test_pip.py

Fails to install modules, only gives error.

Dev pythonista setup.py

---

lib/stashutils/wheels.py

https://github.com/ywangd/stash/issues/364

Fix 'UnicodeDecodeError' when using pip install

---

lib/stashutils/wheels.py

https://github.com/ywangd/stash/issues/372

Fix wheels: Install without top_level.txt

---

bin/mail.py

mail.Encoders is broken, mail.encoders fixes that

Update mail.py (mail.encoders)

---

system/shruntime.py

Add support for Unicode symbols in prompt

---

bin/diff.py
bin/ln.py
bin/ls.py

Hi,
I've created a ln.py bin command for sym linking
a modified ls.py command that shows sym links in yellow and in -l mode with -> as expected.
also included the diff.py command that works like diff using libdiff
Cheers Dave

ln for linking and diff for diffing, ls shows sym links in yellow

---

bin/pip.py

change `INFO_FILE_FODER` to `SITE_PACKAGES_FOLDER,/.package_info/PACKAGE_NAME.json` to fix bug in #420

Pip show:change INFO_FILE_FOLDER

---

bin/pip.py
data/pip_blocklist.json
docs/pip_blocklist.md
tests/pip/test_pip.py

This PR remove usages of non-inclusive language from the code base. We should also strive to not use them in future development. Thanks!

Remove usage of non-inclusive language

---

bin/git.py

Fix suffix stripping of git repo url

---

bin/grep.py
bin/ls.py
lib/libcore.py
tests/grep/__init__.py
tests/grep/data/.hidden
tests/grep/data/another_file.txt
tests/grep/data/case_content.txt
tests/grep/data/file_to.omit
tests/grep/data/nothing_to_be_found.txt
tests/grep/data/subdir/recursive.omit
tests/grep/data/subdir/recursive.txt
tests/grep/test_grep.py
tests/ls/test_ls.py
tests/stashtest.py

grep:
- added output control options
* -n / --line-number (display line numbers)
* -h / --no-filename (suppress file name in output)
* -H / --with-filename (always list file name in output)
* --label (label for stdin in output if file names are shown)
* -L / --files-without-match (only list filenames of files without match)
* -l / --files-with-matches (only list filenames of files with matches)
* -o / --only-matching (only list matching part of lines)
* --color (color matching part of lines)
- added ability for recursive search (option -r / --recursive)
ls:
- added -A / --allmost-all (suppresses . and .. in output)
- added -h / --human (display size in human legible format)
- added -d / --dirs (list directories instead of their content)
- improved output format for -l / --long option
To …

Adding lots of options to grep.py and ls.py

---

.github/workflows/check-code-and-run-tests.yml
bin/git.py
bin/httpserver.py
bin/mail.py
bin/mount.py
bin/ping.py
bin/pip.py
bin/sed.py
docs/porting_guide.md
lib/git/git-branch.py
lib/libdist.py
lib/stashutils/mount_manager.py
system/shui/__init__.py
tests/install/test_getstash.py
tests/pip/test_pip.py
tests/stashtest.py
tools/pythonista_reinstall.py

Let's put Python 3.10 on hold until #463
`ON_TRAVIS` --> `ON_CI`
* https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

Add GitHub Actions on dev branch

---

bin/rm.py

When the verbose option is specified, more detailed explanation will be given if deletion fails.

Added more detailed explanation when it fails

---

CHANGES.md

Tests fail on the `dev` branch even when just making a simple change.
@bennr01 Your review, please.

Tests fail even when fixing a typo

---

.github/dependabot.yml
.github/workflows/check-code-and-run-tests.yml
tests/pip/test_pip.py

* [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
* [Configuration options for the dependabot.yml file - package-ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)

Keep GitHub Actions up to date with GitHub's Dependabot
