ywangd/stash

- bin/pip.py
Fixed the needless move. Added update and remove of pip tracked modules. The package info has been tweaked since last commit so you may need to remove modules to allow pip to track correctly.
I'm debating on adding an update all for updating of all pip installed packages. This could be a lengthy process and the user may want some modules to remain at a earlier version such as Twisted. Twisted 13.x.x works in pythonista where version 14.x.x does not.
> Fixed mv added remove, update

- bin/git.py
This fixes missing imports.  As a warning, in some cases you will get a broken pipe error.  This seems to be caused by commits being made locally and on the server, such that fast forward is not possible.  The solution is to clone the repo again, make changes, then push.  I'm working on merge capability for gitview, which will be portable to stash and hopefully will take cRe of the issue
> Fixed missing imports in git

- bin/git.py
This is an attempt at fixing issue #106 
Unfortunately, it is not as simple as exchanging the URL. We need also to check wether we are using the old version (by checking whether `fetch` is available), clean up the old versions, and reload `dulwich`
> Switch to the jsbain fork of dulwich (issue #106)

- bin/git.py
If the current directory is not a repository, most git commands fail with a `StopIteration` error. This PR tries to fix that and issue a better error message
> better error handling if current directory isn't a repository

- bin/cd.py
when doing cd .. repeatedly, eventually stash crashes when it tries to create the prompt, in a no recoverable way.
the issue is because os.chdir does not raise an error, but os.listdir does.  this fix checks access before chdir.
> fix crash when chdir to folder without access.

- bin/edit.py
With Pythonista 2.0 out, it's now possible to specify a file must be opened in a separate editor tab. This is desirable in the common use case, so I changed to make this the default behaviour, with an '--old_tab' option to reuse an existing editor tab (if any).
Also, while the argument specification made the path argument optional, this wasn't processed correctly. It should work correctly in all cases now (including some special casing if a path is specified neither at the start nor when saving a temporary file).
> Open file in new editor tab by default

- bin/pip.py
be9c22e broke parsing of package names that included - symbol.  This uses regex as defined in the PEP for package name.
> Fix pip parsing of package name

- system/shio.py
This fixes ShIO.readlines() which returned entire buffer string, instead of list of lines.
> Fix ShIO.readlines()

- bin/ftpserver.py
- bin/mc.py
- bin/python.py
- man/manpages.txt
Yet another bunch of bugfixes for the `mc`-command, but also some improvements to the python-command.
**New Command and Files**
- `ftpserver` uses pyftpdlib to start a ftpserver. I frequently use omz`s ftpserver and tought it may be usefull to add to StaSh.
- added a helppage for the manpages. I tought it may be useful to document the behavior of the new `man`-command (in case others want to write manpages; i dont think my english is sufficent to write anything wich is not to hard to read)
**Improvements**
- The `python` command will now pass `_stash` and `__debug__` to the interactive interpreter.
- cleaned up the code of the `mc`-command by removing all unnecessary assignments in `except-clauses`.
**Bugfixes**
- Fixed a bug in `mc` where menu-entries were swapped. I accidently added …
> New command, bugfixes and improvements

- system/shio.py
This fixes that `'\0'` character was wrongly sent to running script, when `CD` key in virtual keyboard was pressed.
This fixes e.g. `CD` terminates `python` command with following exception:
```
stash: <type 'exceptions.TypeError'>: compile() expected string without null bytes
```
> Fix ShIO.readline() handling of Ctrl-D

- bin/gh.py
fix a failed import for the github module.  This was also exacerbated by a buggy github version that was not py2.7 compatible -- if anyone gets issues they can simply delete lib/github to force a more recent version download.
> Fixed github module loading for gh.py

- bin/easy_config.py
See Discussion in #190.
Unfortunately, i have been only able to test this on a 1136 × 640 Display.
However, this script does not use any "magic numbers", so it should work fine on all screen sizes.
Maybe someone can test this?
I was also not able to find a way to automatically add an editor shortcut.
This does not (yet) replace `stashconf`, because `stashconf` is a simple way to temporary change the config. Should i rename `easy_config` to replace `stashconf`?
Also, the `[display] BACKGROUND_COLOR`-option seems to be broken. The background-color is set correctly whenever StaSh is started, but whenever new text is printed, it will have a black background-color.
**EDIT**: Why does the CI-Build fail? I have not changed anything in the threading-system in this commit and the command i have …
> added easy_config

- bin/man.py
- bin/pip.py
- launch_stash.py
- lib/mlpatches/patches.py
- lib/stashutils/core.py
- lib/stashutils/extensions.py
- lib/stashutils/fsi/interfaces.py
- man/manpages.txt
- man/monkeypatching/page_4.txt
- man/monkeypatching/page_5.txt
- man/mounting/page_3.txt
- man/mounting/page_6.txt
- stash.py
- system/shcommon.py
- system/shruntime.py
This pull request makes StaSh more extensible, extends `pip` and contains some fixes.
When StaSh launches, it will now create some folders for extensions:
- `$HOME2/stash_extensions/`: parent directory for extensions (to keep them sorted).
- `$HOME2/stash_extensions/bin/`: This directory is now in `$BIN_PATH`. It may/can/should be used by scripts automatically creating StaSh commands. While it would also be possible to create the commands in `$STASH_ROOT/bin` or `$HOME2/bin`, both have some limitations. `$STASH_ROOT/bin` may be overwritten during an update (or worse, some command may overwrite an important StaSh command). `$HOME2/bin` may contain scripts by the user or other data, which means that no script can be sure it is allowed to overwrite the contents of this directory. Also, due …
> Made StaSh more extensible; pip now handles command line scripts; fixes

- bin/git.py
Adds the "--oneline" option to git log to display the commit history in the form of: 
7-byte-hash First line of commit message
> Git log oneline

- bin/git.py
Bugfix.  Adds relative path support to the file path check when performing a git add.
Current behavior: 
```
[bin]$ git add git.py
bin/git.py does not exist. skipping
[bin]$ cd ..
[stash-dev]$ git add git.py
git.py does not exist. skipping
[stash-dev]$ git add bin/git.py
Adding bin/git.py
```
New behavior.  The relative add now works as expected: 
```
[bin]$ git add git.py
Adding bin/git.py
[bin]$ cd ..
[stash-dev]$ git add git.py
git.py does not exist. skipping
[stash-dev]$ git add bin/git.py
Adding bin/git.py
```
> Relative file handling for git add.

- bin/pip.py
Replaces XML-RPC calls in pip, except package search. Can't find any endpoint and it looks like that people recommends to list simplified index and search in it. Time consuming, not an ideal solution, ... I think that we can live with XML-RPC & search for now. Package is listed immediately and rest is done via JSON.
> XML-RPC replacement #264

- bin/git.py
Don't ask for user name, email on the first git commit if they are already specified in the global user config: `~/.gitconfig`.
> Honor ~/.gitconfig for git user name, email

- system/tests/data/test_102_1.py
- system/tests/data/test_102_2.py
- system/tests/test_threads.py
@ywangd I've tracked down the intermittent CI failures with test 102.  When thread_102_2.py successfully executes first, the resulting output in s begins with "thread_102_2.py".  For this scenario, the original test_102 assertion "find()" was returning "0" (the first position) causing the test to be 0 < 0.  This PR redesigns test 102 to count the number of times the output actually switches between the threads, and defines a minimum number of times we should see it switch.
The selection of "> 2" as the target number of switches was somewhat arbitrary.  My thinking was we at least want to avoid a false pass test pattern of AAAAABBBBB.  In reality, with the way the tests are structured, we should see ABABABABAB (9 changes), but this is not a guarantee.
> Redesigned test 102

- .travis.yml
- bin/cp.py
- bin/crypt.py
- bin/gh.py
- bin/git.py
- bin/grep.py
- bin/latte.py
- bin/mail.py
- bin/which.py
- lib/git/git-merge.py
On the __dev__ branch this time.  This PR replaces #295 which was on the __master__ branch.
It is time to make sure that StaSH can make the transition to Python 3.
* Add flake8 tests in the Travis CI __before_script__.
* Resolve Python 2 undefined names (flake8 F821)
* Remove a few unused imports and ran __isort__ on others.
* Fix #296 with __print()__
Replaces both #293, #294, and #295
> Start testing on Python 3 in allow_failures mode

- bin/pip.py
This is a fix for the `Error: Failed to fetch package release urls` error in `pip`.
The bug was reported by @jphoebe4086824 and the fix was discovered by @nasmatic.
This PR fixes #309.
> pip: fix https error in pip (fix 309)

- docs/py3_todo.md
This is a PR to close a large number of old/fixed issues at once using the github `fix #<issuenumber>` syntax.
Below is a list of all issues which will automatically be closed by merging this PR into `ywangd/master`.
Behind each issue number is a short summary about the issue or why it can be closed.
Other than closing these issues, this PR also removes a few entries from the `docs/py3_todo.md` todo list.
**Py3 related:**
- fix #281 (py3 had not yet been supported)
- fix #261 (python3 pip installation)
- fix #246 (python3 code in python2)
- fix #222 (python3 command in stash)
- fix #200 (pip now works (at least partially) with python3)
- close #197 (general pythonista3 compatibility thread)
**Questions which have been answered / unfixable bugs:**
- close #310 (pip installation with c …
> Close old/fixed issues

- bin/git.py
Commit #3f958a9 replaced an import of urlparse module, urlparse function.  Not surprisingly, this breaks most uses of git.  This commit replaces urlparse usage throughout git.py.  This should be pulled into master asap.
> Correct urlparse break from 3f958a9

- bin/git.py
When ~./gitconfig does not exist, stacked config does not work as expected.  This change allows user to specify whether to use global config, or not, and creates the .gitconfig file if needed
> Correct problem introduced in #286

- bin/easy_config.py
- system/dummyobjc_util.py
- system/shscreens.py
- system/shterminal.py
- tests/pip/test_pip.py
After two years, I finally found the bug!
As mentioned in PR #207, the backgroundcolor (and textcolor) system was broken. When using non-black background-colors, the background would have the correct color, but the text would always have black background and white text.
This PR fixes this bug, but reduces the color range for the terminal from full RGB to the colors specified in `$STASH_ROOT/system/shscreens.py` (excluding `smoke`). Additionally, the values of some colors have been adjusted to match the terminal backgroundcolors.
**Fixes:**
- fix background and text colors
- fix tests for pip search (but will most likely break again in the future)
**Improvements:**
- `easy_config.py` was updated to reflect these changes
- `easy_config.py` will now report `$SELFUPDATE_TARGET`.
- The …
> Fix broken Text- & Backgroundcolor

- lib/stashutils/wheels.py
- tests/pip/test_pip.py
Hi,
this PR fixes the broken test for `pip search` (as written in #347).
I already tried to fix it previously, but apparently pypi search results vary from time to time. Before this change, the test expected `pip search pytest` to print `pytest`, `pytest-translations` and `pytest-socket`. Now it only expects `pytest`.
This PR also fixes a bug in the `pip install` wheel logic. There was a bug that for some packages, all subpackages (e.g. `mypackage.subpackages`) would be installed directly in `site-packages-*` instead of their parent package. This should now be fixed.  See [this forum thread](https://forum.omz-software.com/topic/5340/pythonista-3-stash-plotly-i-m-close-to-a-meltdown) for details.
> Fix bug in pip wheel installation; Fix test for 'pip search'

- bin/gh.py
- bin/pip.py
- core.py
- lib/libversion.py
- lib/stashutils/wheels.py
- tests/misc/test_libversion.py
- tests/pip/test_pip.py
Hi,
In the last few weeks,  I have been on a successful hunting bugs in `pip`.
These improvements mainly target version-related behavior. I also fixed the dependency installation for `gh`.
- **general:**
- version bump to `0.7.2`
- `pip`:
- **improvement:** add the `--only-binary`, `--prefer-binary` and `--no-binary` arguments to `pip`. These arguments allow the use to specifically set preference between source and wheel releases. Suggested by @jsbain in [this forum thread](https://forum.omz-software.com/topic/5381/stash-alternatives-for-pip/2)
- **improvement**: more verbose output. Also more normal output (e.g. which packages requires a dependency).
- **improvement/bugfix:** `pip` now respects `python_requires`. This should greatly improve py2/py3 compatibilty for `pip`.
- **bugfix:** …
> various improvements and bugfixes for pip and gh

- bin/crypt.py
- bin/pip.py
This commit fixes #381, where setup.py may have Unicode symbols. In this case, setup.py is passed as a bytestring to avoid guessing the encoding of setup.py (or to assume it is ASCII).
> Fix encoding error for executing setup.py

- bin/curl.py
- data/pip_blacklist.json
Content to be downloaded may contain raw bytes, so it is best to write it as bytes directly to the file (without decoding).
> Fix curl not downloading binary blobs

- bin/pip.py
add command `pip show package`.
there is a problem:
It will download info file from pypi after installed the package,so the package which installed by the previous install function may have no 'info.json',there are tow way to solve this problem:using option -f or reinstall the package.
TODO:
> pip:add subcommand show

- bin/mv.py
Fixed bug:
here is the file tree in current directory:
.
├──  test
├──  ├──  init.py
├──  dir
├──  ├──  test
├──  ├──  ├──  init.py
After I type`mv test dir`,it will become:
├──  dir
├──  ├──  test
├──  ├──  ├──  init.py
├──  ├──  ├──  test
├──  ├──  ├──  ├──  init.py
> Fixed bug in mv.py

- data/pip_blacklist.json
Fix for issue #407 (gevent uses c code, grequests uses gevent as a dependency)
> Add gevent and grequests to blacklist

- core.py
There was a typo in core.py where it said 'NOTEST' instead of 'NOTSET'.
> Fixed typo in core.py

- bin/rm.py
In rm.py there where checks for isfile(...) and isdir(...) but none for islink(...) leading to problems trying to use rm.py to delete a link.
> Fixed rm.py to remove links as well

- bin/printhex.py
range() produces an iterable in Python 3 which subsequently leads to problems. Putting a list() around it fixed the problem. Also optimized decoding and added os.path.expanduser to allow filenames like ~/some/file.ext that may not get resolved
by the stash shell (like in printhex `which printhex`).
> Made printhex.py work for Python 2 and 3

- bin/edit.py
Added os.path.expanduser to edit.py to allow commands like "edit `which git`" where the shell does not seem to expand the tilde returned from which.
> Added os.path.expanduser to edit.py

- .gitignore
Using eclipse for development and debugging, the files .project, .pydevproject and the directory .settings is added to the root of the project. To not have those distributed with the project files, I added according lines to .gitignore.
> Added Eclipse meta files to .gitignore

- getstash.py
* This comma has been most probably been left out unintentionally, leading to string concatenation between the two consecutive lines. This issue has been found automatically using a regular expression.
> fix: Missing comma in `UNWANTED_FILES`

- lib/libversion.py
- lib/stashutils/wheels.py
In most cases wheels have additional requirements like `brotli; platform_python_implementation == 'CPython' and extra == 'brotli'`.
My changes take care about that. In addition checking for `platform_python_implementation`, `platform_system` and `sys_platform`.
Next patch `libversion` to take care of wildcard version match like `1.*`
> patch wheels to take care of additional requirements

- system/shthreads.py
- system/shui/pythonista_ui.py
`Thread.is_alive()` was added in ___Python 2.6___ so we can change `.isAlive()` to `.is_alive()` everywhere to be compatible with all versions of Pythonista.
* https://docs.python.org/2/library/threading.html#threading.Thread.is_alive
* https://github.com/ywangd/stash/pull/463#discussion_r1126007645
> Replace Thread.isAlive() with Thread.is_alive() AGAIN

- core.py
- getstash.py
WIth the newest pythonista version dropping py2 completely, It's time to move on an deprecate py2. (Goodbye python 2.7, you were my one true love).
This PR bumps the StaSh version to `0.8.0` and updates the `getstash`-script to prevent upgrades on py2 to versions `>0.7.4`. Technically, semantic versioning would require us to increment the major version due to breaking changes, but do we really have enough py3 compatibility to justify version `1.0.0`?
> Deprecate py2

- system/shcommon.py
- system/shui/pythonista_ui.py
Pythonista 3 was recently upgraded to python3.10. This fix mirigates plist.py:8: DeprecationWarning: The readPlist function is deprecated, use load() instead pl=plistlib.readPlist(fileName)
> Fix for #484: module 'plistlib' has no attribute 'readPlist'

- .github/workflows/check-code-and-run-tests.yml
- bin/jobs.py
- lib/libdist.py
- system/shiowrapper.py
- system/shparsers.py
- system/shruntime.py
Fixes: #462 
```python
SITE_PACKAGES_DIR_NAME = "site-packages"
if sys.version_info < (3, 10):  # Pythonista < v3.4
SITE_PACKAGES_DIR_NAME += "-3"
```
@bennr01 @ywangd Your review, please.
> Fix site-packages for Pythonista >= v3.4
